### ISSUE TITLE
Extend visualization with features

### ISSUE THREAD

**Issue by fouweric** [fouweric/wikileaks-data-analytics#13]
Extend #12 with features such as 
- A slider bar from 0 to MAX taking a current value k which hides all edges of the graphs with weights < k
- A slider bar from 0 to MAX taking a current value k which displays only strongest (in weights) k clusters
- others ?

**Comment by agulfy** [comment]
1b250472e93ae3db9ecd89bf70d523c8316845ee Added the two filters suggested but I'm not familiar with angular enough to connect variables/sliders on the front-end. Somebody else with more experience can improve it from here

**Comment by fouweric** [comment]
Nice!
