### ISSUE TITLE
PageRank top-k analysis

### ISSUE THREAD

**Issue by fouweric** [fouweric/wikileaks-data-analytics#14]
Do the page rank analysis

Input: cables
Output: top-k list

**Comment by fouweric** [comment]
Nice! Did you produces a .json visualization file :dancers: ?

**Comment by fouweric** [comment]
@agulfy I see, you have done the page rank analysis. Then, there are no graph to produce, only an top-k list.

But it is not the purpose of this issue: This issue asks for grouping documents into clusters.

**Comment by fouweric** [comment]
Ok, this issue is renamed (and issue #22 was re-created).

@agulfy Can you add the results of this analysis into either the website or at least a .txt file?

**Comment by agulfy** [comment]
I built the initial graph to be processed and I thought the grouping/clustering would be completed in #20.

I can put the pagerank results on the website though.

**Comment by fouweric** [comment]
#20 is "determining how" and not "implement" or "code" the clustering algo
Yes, your reference graph can be re-used in #22
