### ISSUE TITLE
Build proper-noun database

### ISSUE THREAD

**Issue by fouweric** [fouweric/wikileaks-data-analytics#15]
Input: plusD-database
Output: a set of table where indexes are documentsID and attributes are names, places, etc..

**Comment by fouweric** [comment]
@M-Eng Is your problem with spark and java 1.8 solved? How is the work going :))) ?

**Comment by fouweric** [comment]
Task completed.
Output is in **hdfs://projects/wikileaks/NER/fullClassification/**

`data.map(x => x.substring(1,x.size-1)).map(_.split(",")).map(t => (t(0),t(1),t(2)))`
to have a `(docId, Topic, Value)` tuple from the initial `RDD[(DocId,Tag,Value)]`

Credits go to @M-Eng

**Comment by M-Eng** [comment]
I have just added an extended output for this one with more tags, I think it might be useful. (**MONEY, PERCENT,DATE,TIME** plus the usual one LOCATION, PERSON,ORGANIZATION)
you can find it in 
**hdfs://projects/wikileaks/NER/extendedClassification/**

**Comment by fouweric** [comment]
@M-Eng I saw also the MISC tag in the old classification, did you removed it?

**Comment by M-Eng** [comment]
No you are right the old classification also contain a MISC tag, but the new one does not. You can use both classification (I haven't removed the old one) but they are done with different models which mean that for the same tags the results might be slightly different.

**Comment by fouweric** [comment]
@M-Eng I am exploring the LOCATIONs produced by your NER.fullClassification analysis, and there are a lot of double or even triple concatenated locations.
e.g. Jamaica Jamaica, Jamaica Mexico, Jamaica Washington
I even found: "Washington Chicago S Francisco Los Angeles Washington" as a location entry

**Can you do something about this issue?**

Also, there often appears a declination of the same location with one letter in front of.
e.g. C Rome, D Rome, B Rome, E Italy

**Comment by M-Eng** [comment]
I have the same issue with the transaction analysis. The concatenation come from the fact that the document are not only text. For example the header of table might be concatenated to a single Location.
And I don't know how to solve this, I don't have much control on the NER, one solution would be to discard the weird Location (but how to detect them?). Another way would be to only keep cable that are text but we will probably loose 60% of the documents.
I'm not sure I will have the time to look more into that, is it really necessary? ( most of the location should be correct?)
