### ISSUE TITLE
Clustering algo(s) Implementation

### ISSUE THREAD

**Issue by fouweric** [fouweric/wikileaks-data-analytics#20]
Determine how to
 - Implement the clustering algorithm  for issues of [Explore cables via dependencies graph](https://github.com/fouweric/wikileaks-data-analytics/milestones/Explore%20cables%20via%20dependencies%20graphs)

**Comment by fouweric** [comment]
A recursive (on sub-graphs) call of the min. cut algo with a stop condition on clusters connectivity (min. cut value) perfectly answers our needs.
It sound like a way to explore.

**Comment by fouweric** [comment]
[GraphX](https://spark.apache.org/docs/latest/graphx-programming-guide.html) is the Spark library for graphs

**Comment by fouweric** [comment]
my 3 commits 9f36de375770c9850d473c1cb15c3c7fe3a008c8, 1dde0e35b634f19d6f5b9e10dc152a5369e62b5c, 82372d923eeb8bb1abadde9f4ee47e7041cd9ab5 are mentioning issue #21 but it is a mistake, they belong to this issue (#20)

sorry for the confusion =)

**Comment by fouweric** [comment]
[PIC algo seems a way of doing the clustering](https://spark.apache.org/docs/latest/mllib-clustering.html#power-iteration-clustering-pic)
However, it requieres the MLlib from spark 1.3.0

**Comment by agulfy** [comment]
Looks like this is done already with PIC. I found an alternative algorithm named [MCL](http://micans.org/mcl/), and a [scala implementation](http://cobweb.cs.uga.edu/~jam/scalation_1.0/src/main/scala/scalation/analytics/MarkovClustering.scala)
Leaving this here in case we want to experiment with something else.

Also close issue with commit 6c0853ab2c1567d2452e26e222736fff62715f98 ?

**Comment by fouweric** [comment]
Do we close the issue once we have tried the algos on more graphs?
