### ISSUE TITLE
Topic classification 

### ISSUE THREAD

**Issue by M-Eng** [fouweric/wikileaks-data-analytics#21]
# Introduction
Topic classification could be useful in the project for various things.
We could use it as a clustering algorithm #20. We could also use the result to do more advanced processing, (summarizing every topics, use the topic to find particular type of documents etc ...)

# How does it works
We would use the Latent Dirichlet Algorithm (LDA), it would work on the whole set of documents and only take a few parameters as input (Number of topics wanted, number of iterations). 
So it would require a little parameter tuning.  

# Library
I have found a nice library that implement LDA in Scala in the Stanford natural language processing group ( http://nlp.stanford.edu/software/tmt/tmt-0.4/ ). 
So i think it will be possible to use this in spark with not to much trouble.

# Steps

* Format the input
    * Tokenize
    * Clean
* Train the model
   * Parameter tuning 
* Process the output
   * ...

I am currently working on it. I will commit my code as soon as I have something working.

**Comment by M-Eng** [comment]
After having trouble compiling the library from the Stanford NLP group, I found out that the new version of Spark (1.3.0) contain an implementation of LDA in the MLLIB.
But the cluster is running the 1.2.1 version do you think it's possible to do the upgrade?

**Comment by CanGuzelhan** [comment]
Python has a library for LDA too. If it seems to be hard on Scala, we can switch to Python.

Envoyé depuis mon HTC

----- Reply message -----
De : "M-Eng" <notifications@github.com>
Pour : "fouweric/wikileaks-data-analytics" <wikileaks-data-analytics@noreply.github.com>
Objet : [wikileaks-data-analytics] Topic classification (#21)
Date : mer., avr. 15, 2015 14:39


After having trouble compiling the library from the Stanford NLP group, I found out that the new version of Spark (1.3.0) contain an implementation of LDA in the MLLIB.
But the cluster is running the 1.2.1 version do you think it's possible to do the upgrade?

**Comment by fouweric** [comment]
@M-Eng Spark 1.2.1 does not contain the LDA algos?

**Comment by M-Eng** [comment]
No it has been added in the last update. 
I think it would be the easiest option (because it's already parallelize, and we don't have to do the Spark integration).

If it's not possible I have found a more recent scala library for the LDA:
http://factorie.cs.umass.edu/index.html

**Comment by CanGuzelhan** [comment]
Does it have to be in Scala ? Python does the same job.

Envoyé depuis mon HTC

----- Reply message -----
De : "M-Eng" <notifications@github.com>
Pour : "fouweric/wikileaks-data-analytics" <wikileaks-data-analytics@noreply.github.com>
Cc : "Güzelhan Can" <can.guezelhan@epfl.ch>
Objet : [wikileaks-data-analytics] Topic classification (#21)
Date : mer., avr. 15, 2015 19:49


No it has been added in the last update.
I think it would be the easiest option (because it's already parallelize, and we don't have to do the Spark integration).

If it's not possible I have found a more recent scala library for the LDA:
http://factorie.cs.umass.edu/index.html

**Comment by fouweric** [comment]
@ElSeidy perhaps know if there is a way

**Comment by fouweric** [comment]
@CanGuzelhan Don't know if it is possible =/

**Comment by CanGuzelhan** [comment]
I have been telling this for weeks. Of course it is.

Envoyé depuis mon HTC

----- Reply message -----
De : "Frédéric Ouwehand" <notifications@github.com>
Pour : "fouweric/wikileaks-data-analytics" <wikileaks-data-analytics@noreply.github.com>
Cc : "Güzelhan Can" <can.guezelhan@epfl.ch>
Objet : [wikileaks-data-analytics] Topic classification (#21)
Date : mer., avr. 15, 2015 20:04


@CanGuzelhan<https://github.com/CanGuzelhan> Don't know if it is possible =/

**Comment by M-Eng** [comment]
Yes it's possible, but I don't think it will help (we still have to do the integration in Spark). I just choose Scala because I'm more familiar with it and it's more consistent with the other parts of the project that are also in Scala.

**Comment by M-Eng** [comment]
I'm switching with Can, so I'm no longer working on this but I'll work on #15

**Comment by fouweric** [comment]
@M-Eng @CanGuzelhan [Question posted on big-data forum](http://moodle.epfl.ch/mod/forum/discuss.php?d=197066)

**Comment by CanGuzelhan** [comment]
Soon, topics should be extracted from contents. Is there any way to make a graph where we choose some topics and see which documents are linked according to chosen topics ?
