### ISSUE TITLE
Mine the data with Spark

### ISSUE THREAD

**Issue by fouweric** [fouweric/wikileaks-data-analytics#26]
Depends on the proper nouns clustering from #29

**Comment by ketjuni2** [comment]
@fouweric  see the abbreviation data on the project folder in the cluster  hdfs:///projects/wikileaks/wardiary-csv/abbreviations.txt

**Comment by fouweric** [comment]
@ketjuni2 Very useful! Thanks!

**Comment by fouweric** [comment]
Actual data size is 300MB, no need to run this code on the cluster (as I did until now..)
