### ISSUE TITLE
Settup the plusD plan

### ISSUE THREAD

**Issue by fouweric** [fouweric/wikileaks-data-analytics#3]
The first task for this group is to
- [x] settup the plan

Actual group: @agulfy ,@fouweric
Post here if you are interested in joining.

**Comment by fouweric** [comment]
@agulfy said (by mail)

We basically have few options:
- Cut our losses and work with whatever we have.
- Have two teams work on seperate problems:
    - Workpackage 1: Other cables are still available on the website similar to https://www.wikileaks.org/plusd/cables/1973ROME11385_b.html We can try to crawl the website and parse these documents. Assign a 2-3 person group on crawling and cleaning the missing data
    - Workpackage 2: Assuming we will have a common data schema when WP1 is finished, develop a backend that we can use / do a simple application.

**Comment by fouweric** [comment]
@agulfy said (by mail)

By the way,
The previous cablegate dataset is also available as sql dump. so it is almost trivial to import it into any database.
https://archive.org/download/WikileaksWarDiarySql/afg-war-diary.sql.7z

**Comment by fouweric** [comment]
@fouweric said (by mail)

Then, should we first explore and compare the .torrent and the wikileaks website to evaluate the assumption of WP2:
- << Workpackage 2: Assuming we will have a common data schema when WP1 is finished" .. >>

Can we reformulate this hypothesis to:
- there exists a common representation for the cablegate and the (Kissinger, Carter) cables ?

**Comment by fouweric** [comment]
@agulfy said (by mail)

(id, date, refid, classification, origin, destination, header, content) The csv has these attributes, and kissinger cables also have the same attributes on their relevant webpage. So I think your re-wording is accurate.

But I have to note that the websites contain more information than what is given on the csv/sql dump. One of the more interesting features in the website is “ References to this document in other cables/References in this document to other cables” field. We might use these to construct graphs. But it data crawling from the website becomes inevitable.

Shall we move this discussion to github?

**Comment by fouweric** [comment]
Moving a mail thread to github is a bit painful :laughing: 
Ok, let's continue to discuss the plan here.

I agree. The website contains a lot more *useful information* and crawling becomes inevitable.

Then, we should begin by creating a data crawling (script/mapreduce/spark/other?) application?

**Comment by agulfy** [comment]
I will try to divide the work a little here...
We can have two applications, one to download everything in html and another to parse the html document and extract useful bits. I think that's reasonable. What's your opinion?

@patceline and @HKassir72 can you assign 2 more members to this part to do the script or parsing? 

We will eventually need to have someone to install/setup the database on the cluster but I guess there are already people responsible for that?

**Comment by fouweric** [comment]
I have a small variation of what you proposed @agulfy 

From http://search.wikileaks.org/plusd/ , there are
1707500+367174+251287 = 2,325,961 documents

If we download **5 pages** per second
2325961/5/60/60/24 = ~5 days to download them all

If we download **50 pages** per second
2325961/50/60/60/24 = ~12 hours
**100 pages** /sec => ~6 hours etc..

- Point 1: we will really benefit from parallelization in the download scripts.

If we have the page_id like **1973STATE097844_b** , you can easily tweak URLs to access the data: http://search.wikileaks.org/plusd/cables/1973STATE097844_b.html .

- Point 2: The hard task is hence to get the biggest set of page_id we can.

Then, regarding these 2 points, we can modularize our code as follow:
- The discoverers(parallelizable?): Discover the biggest page_id set and save it in our DB
- The downloaders(parallelizable?): asks the DB for an unfetched page_id, fetch the associated HTML page, and save it back in the DB
- The extractors(parallelizable?): Take an unprocessed fetched HTML page from the DB, extract fields, save the fields back into the DB

What do you think?

Heard that @fbriant was interested about the database settup.

**Comment by agulfy** [comment]
I agree on point 1... 

On page ids:
I think blindly trying to figure out valid page_ids is unnecessary.
We can have the full list of results with: https://www.wikileaks.org/plusd/?q=&qtfrom=1966-01-01&qtto=2010-12-31#result Clicking on "next 500" *a few (heh)* times is easy with javascript and then you can get all page_ids from the resulting file.

Do we really need to save all html files in a db? We could just leave them as plain text under some directory in the cluster.

**Comment by fouweric** [comment]
Yes, it is a bad idea to guess page ids :)
And true, we can extract them from list of results.
Yes sorry, saving HTML files to dB => saving them to hdfs.

But Mhh, you cannot click more than once the "next 500".. Try it :)
You will need another strategy =), and it seems like a non trivial task
which deserves a place in our plan. (?) by the way, I am interested in
taking this task!

Is the plan ok? Should we create an issue for each task of the plan and
assign it to a milestone?

**Comment by agulfy** [comment]
I assumed "next 500" would go indefinitely... How about we modify qtfrom and qtto parameters at url to divide the result page into small chunks?

We can create the issues. I still think that 31 March is a good deadline for both these tasks.

**Comment by fouweric** [comment]
Yes, it looks like a solution.

Ok, can you create the three tasks?
- Page ids fetching
- HTML fetcher
- HTML parsers

Ok for 31 March :)

**Comment by agulfy** [comment]
I'm just creating two tasks fyi:

-data crawling: page_ids fetching  & html fetcher (second part is just "$ wget URL" )
-data cleaning: Html parser

I will close this task after we get two more members assigned
