### ISSUE TITLE
WP3 - Schema

### ISSUE THREAD

**Issue by agulfy** [fouweric/wikileaks-data-analytics#6]
For the output of #5, we need a schema. @bhyassine will be working on this.

**Comment by fouweric** [comment]
Assuming commit bd7594f8cd4b41b77229fede057b141f7681fe7b closed it

**Comment by agulfy** [comment]
I have a few questions/suggestions for the schema related to commit 92648dcd8b8dc03c3b01e9486fd23ab669fc007d.

* There is no field for the title of the cable.
* There is no table for "TO:" (receivers of the cable)
* I understand that giving id/types to certain fields such as classifications etc, can save space etc but it makes things messy.

and other stuff. Can you check the commit and come back to me?

**Comment by agulfy** [comment]
completed 30fd37fd337f206221b206b8e326c69d9c7abaae
