### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by bhyassine** [fouweric/wikileaks-data-analytics#8]
Hi guys,
I prepared the Design of the database, but when I don't have the permission to push the files, I think that I am not yet assigned as a contributor for this repository.

**Comment by fouweric** [comment]
@patceline Add @bhyassine to repo or transfer ownership to @HKassir72 so he can do it?

**Comment by agulfy** [comment]
Hey @bhyassine, the repo is transferred now. Can you try again and if it doesn't work contact @HKassir72?

**Comment by fouweric** [comment]
I am asking @patceline for repo transfer, @bhyassine will give you the rights as soon as I get the ownership.

**Comment by fouweric** [comment]
Ownership transferred.
@bhyassine You are now a valid collaborator.
