### ISSUE TITLE
Schema to concrete DB

### ISSUE THREAD

**Issue by fouweric** [fouweric/wikileaks-data-analytics#9]
Bringing the DB schema of issue #6 into a concrete DB.

**Comment by fouweric** [comment]
@bhyassine As you wrote the schema, do you want to work on this issue?

**Comment by HKassir72** [comment]
Guys, so did you decide how your concrete DB will be? 
Are you gonna use SPARK and SQL SPARK? Or what do you plan to do.

**Comment by agulfy** [comment]
not really. by the way @bhyassine does not respond to anything for more than a week. I think I am going to do the schema myself again. It would be great if someone looked into this in the mean time.

**Comment by agulfy** [comment]
@M-Eng and/or @CanGuzelhan can you help with this?

**Comment by CanGuzelhan** [comment]
Sure

Envoyé depuis mon HTC

----- Reply message -----
De : "agulfy" <notifications@github.com>
Pour : "fouweric/wikileaks-data-analytics" <wikileaks-data-analytics@noreply.github.com>
Cc : "Güzelhan Can" <can.guezelhan@epfl.ch>
Objet : [wikileaks-data-analytics] Schema to concrete DB (#9)
Date : dim., avr. 5, 2015 19:57


@M-Eng<https://github.com/M-Eng> and/or @CanGuzelhan<https://github.com/CanGuzelhan> can you help with this?

**Comment by fouweric** [comment]
Didn't yassine committed the scheme last week?

**Comment by agulfy** [comment]
not seeing anything here

**Comment by fouweric** [comment]
Yes true, yassine has not commit yet.

**Comment by fouweric** [comment]
@agulfy @M-Eng @CanGuzelhan See commit bd7594f8cd4b41b77229fede057b141f7681fe7b

**Comment by HKassir72** [comment]
Guys we need to decide on what the DB will be. Anybody took a look on SPARKSQL? I did and I think it will do the job. Please let us decide on that.

**Comment by fouweric** [comment]
SPARKSQL will fit well! +1 for the SPARKSQL

**Comment by ElSeidy** [comment]
:+1:

**Comment by agulfy** [comment]
Alright, I suppose the output of #5 should be a csv instead of sql commands?

**Comment by agulfy** [comment]
completed 30fd37fd337f206221b206b8e326c69d9c7abaae
